comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 50%
        if_not_found: error
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 0%
        if_not_found: error
