services:
  app:
    container_name: blog_development
    build:
      context: .
      dockerfile: .envs/development/ruby/Dockerfile
    image: blog_image:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec puma"
    volumes:
      - .:/blog
    ports:
      - "30001:3000"
    depends_on:
      - postgres
    networks:
      - internal
    env_file:
      - .env
    tty: true
    stdin_open: true

  postgres:
    image: postgres
    ports:
      - "54321:5432"
    env_file:
      - .env
      - .env.docker
    volumes:
      - ./data:/var/lib/postgresql
    networks:
      - internal

  redis:
    image: redis:7.2.12
    env_file:
      - .env.docker
    ports:
      - 63791:6379
    command: ["bash", "-c", "docker-entrypoint.sh --requirepass $${REDIS_PASSWORD}"]
    networks:
      - internal

  # Only turn these services on for testing log only
  alloy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: grafana/alloy:latest
    command: [
      "run", "/etc/alloy/config.river"
    ]
    volumes:
      - .envs/stag/alloy/alloy-config.river:/etc/alloy/config.river
      - ./log:/var/log/app
    env_file:
      - .env.docker

  cron:
    container_name: blog_cron
    image: blog_image:latest
    command: bash -c "whenever && whenever --update-crontab && sudo cron -f"
    volumes:
      - .:/blog
    depends_on:
      - postgres
      - redis
      - app
    networks:
      - internal
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://:Aa123456@redis:6379/1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Aa123456
      - EVENT_REDIS_DB=2
      - DB_HOST=postgres
      - DB_PORT=5432
    env_file:
      - .env

networks:
  internal:
    driver: bridge
