services:
  app:
    container_name: blog_prod
    mem_limit: 300m
    build:
      context: .
      dockerfile: .envs/stag/ruby/Dockerfile
    image: blog_image:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/blog
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - internal
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://:luudai198@redis:6379/12
      - NODE_OPTIONS=--openssl-legacy-provider
    env_file:
      - .env

  nginx:
    mem_limit: 10m
    build:
      context: .envs/stag
      dockerfile: nginx/Dockerfile
      args:
        - DOMAIN_WEB=${DOMAIN_WEB}
    image: nginx_prod
    volumes:
      - ./log:/app/log
    env_file:
      - .env.docker
    ports:
      - 80:80
      - 443:443
    networks:
      - internal

  postgres:
    mem_limit: 50m
    image: postgres
    container_name: blog_database_prod
    ports:
      - "5432:5432"
    env_file:
      - .env
      - .env.docker
    volumes:
      - /opt/db:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    mem_limit: 50m
    image: redis:7.2.12
    env_file:
      - .env.docker
    ports:
      - 6379:6379
    command: ["bash", "-c", "docker-entrypoint.sh --requirepass $${REDIS_PASSWORD}"]
    networks:
      - internal

  sidekiq:
    mem_limit: 250m
    container_name: blog_sidekiq
    image: blog_image:latest
    command: bash -c "service cron start && whenever && whenever --update-crontab && bundle exec sidekiq"
    volumes:
      - .:/blog
    depends_on:
      - postgres
      - redis
      - app
    networks:
      - internal
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://:luudai198@redis:6379/12
    env_file:
      - .env

  alloy:
    container_name: alloy
    mem_limit: 80m
    image: grafana/alloy:latest
    command: [
      "run", "/etc/alloy/config.river"
    ]
    volumes:
      - .envs/stag/alloy/alloy-config.river:/etc/alloy/config.river
      - ./log:/var/log/app
    env_file:
      - .env.docker

networks:
  internal:
    driver: bridge
