enum:
  post:
    status:
      publish: publish
      draft: draft

models:
  reminder:
    day:
      day_of_week: [Mon, Tue, Wed, Thu, Fri, Sat, Sun]
      working_day: [Mon, Tue, Wed, Thu, Fri]
      weekend: [Sat, Sun]
      monday: 'Mon'
      tuesday: 'Tue'
      wenesday: 'Wed'
      thursday: 'Thu'
      friday: 'Fri'
      saturday: 'Sat'
      sunday: 'Sun'
  post:
    statistic:
      post_per_week: post_per_week
      post_per_month: post_per_month
    cache_limit: 20 # posts
  announcement:
    views:
      max_display: 3
  user:
    password: !ruby/regexp /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}\z/

target:
  annually_posts_count: 12

statistic:
  default_statistic_decimal_place: 2
